version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: squid
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U squid"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  squid:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: example-squid:latest
    container_name: example-squid
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=squid
      - DB_USER=squid
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - REDIS_URL=redis://:redis@redis:6379
      - PROCESSOR_PROMETHEUS_PORT=3000
      - GQL_PORT=4350
      - CHAIN_RPC=https://eth-mainnet.public.blastapi.io
      - CONTRACT_ADDRESS=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
    ports:
      - "3000:3000"
      - "4350:4350"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  redis_data:
